const frenchVocabData = {
  courses: [
    {
      "id": 1,
      "name": "600 mots",
      "url": "600_mots",
      "description": "Lorem ipsum dolor",
      "lessons": [
        {
          "id": 1,
          "name": "Verbes. Part 1",
          "url": 'verbes_part_1',
          "words": [
            {"id": 1, "english": "abandonner", "russian": "покидать"},
            {"id": 2, "english": "accepter", "russian": "принимать"},
            {"id": 3, "english": "accompagner", "russian": "сопровождать"},
            {"id": 4, "english": "acheter", "russian": "покупать"},
            {"id": 5, "english": "adorer", "russian": "обожать"},
            {"id": 6, "english": "agir", "russian": "действовать"},
            {"id": 7, "english": "aider (эдэ)", "russian": "помогать"},
            {"id": 8, "english": "aimer (эмэ)", "russian": "любить"},
            {"id": 9, "english": "ajouter", "russian": "прибавлять"},
            {"id": 10, "english": "aller", "russian": "идти"},
            {"id": 11, "english": "amener (амэнэ)", "russian": "вести, тащить"},
            {"id": 12, "english": "amuser", "russian": "развлекать"},
            {"id": 13, "english": "annoncer", "russian": "объявлять"},
            {"id": 14, "english": "apercevoir", "russian": "замечать"},
            {"id": 15, "english": "apparaître", "russian": "появляться"},
            {"id": 16, "english": "appeler", "russian": "называть"},
            {"id": 17, "english": "apporter", "russian": "приносить"},
            {"id": 18, "english": "apprendre", "russian": "учиться"},
            {"id": 19, "english": "approcher", "russian": "приближать"},
            {"id": 20, "english": "arranger", "russian": "размещать, организовывать"},
            {"id": 21, "english": "arrêter", "russian": "останавливать, арестовывать"},
            {"id": 22, "english": "arriver", "russian": "приезжать"},
            {"id": 23, "english": "asseoir (асуа)", "russian": "садиться"},
            {"id": 24, "english": "assurer", "russian": "уверять"},
            {"id": 25, "english": "attaquer", "russian": "атаковать, нападать"},
          ]
        }, {
          "id": 2,
          "name": "Verbes. Part 2",
          "url": 'verbes_part_2',
          "words": [
            {"id": 1, "english": "atteindre (атандр)", "russian": "достигать"},
            {"id": 2, "english": "attendre (атондр)", "russian": "ждать"},
            {"id": 3, "english": "avancer", "russian": "продвигаться"},
            {"id": 4, "english": "avoir", "russian": "иметь"},
            {"id": 5, "english": "baisser", "russian": "опускать"},
            {"id": 6, "english": "battre", "russian": "бить"},
            {"id": 7, "english": "boire", "russian": "пить"},
            {"id": 8, "english": "bouger", "russian": "шевелить"},
            {"id": 9, "english": "brûler", "russian": "жечь"},
            {"id": 10, "english": "cacher", "russian": "прятать"},
            {"id": 11, "english": "calmer", "russian": "успокаивать"},
            {"id": 12, "english": "casser", "russian": "ломать, портить"},
            {"id": 13, "english": "changer", "russian": "менять"},
            {"id": 14, "english": "chanter", "russian": "петь"},
            {"id": 15, "english": "charger", "russian": "грузить"},
            {"id": 16, "english": "chercher", "russian": "искать"},
            {"id": 17, "english": "choisir", "russian": "выбирать"},
            {"id": 18, "english": "commencer", "russian": "начинать"},
            {"id": 19, "english": "comprendre", "russian": "понимать"},
            {"id": 20, "english": "compter", "russian": "считать"},
            {"id": 21, "english": "conduire", "russian": "вести, управлять"},
            {"id": 22, "english": "connaître", "russian": "знать"},
            {"id": 23, "english": "continuer", "russian": "продолжать"},
            {"id": 24, "english": "coucher", "russian": "укладывать спать"},
            {"id": 25, "english": "couper", "russian": "резать, стричь"},
          ]
        }, {
          "id": 3,
          "name": "Verbes. Part 3",
          "url": 'verbes_part_3',
          "words": [
            {"id": 1, "english": "courir", "russian": "бежать"},
            {"id": 2, "english": "couvrir", "russian": "застилать, прикрывать"},
            {"id": 3, "english": "craindre", "russian": "бояться, опасаться"},
            {"id": 4, "english": "crier", "russian": "кричать"},
            {"id": 5, "english": "croire", "russian": "верить, считать"},
            {"id": 6, "english": "danser", "russian": "танцевать"},
            {"id": 7, "english": "décider", "russian": "решать"},
            {"id": 8, "english": "découvrir", "russian": "открывать"},
            {"id": 9, "english": "dégager (дэгажэ)", "russian": "выкупать, освобождать"},
            {"id": 10, "english": "demander", "russian": "просить"},
            {"id": 11, "english": "descendre", "russian": "спускаться"},
            {"id": 12, "english": "désoler", "russian": "огорчать"},
            {"id": 13, "english": "détester", "russian": "ненавидеть"},
            {"id": 14, "english": "détruire", "russian": "разрушать"},
            {"id": 15, "english": "devenir", "russian": "делаться, становиться"},
            {"id": 16, "english": "deviner", "russian": "угадывать"},
            {"id": 17, "english": "devoir", "russian": "быть должным"},
            {"id": 18, "english": "dire", "russian": "говорить"},
            {"id": 19, "english": "disparaître", "russian": "исчезать, вкрываться"},
            {"id": 20, "english": "donner", "russian": "давать"},
            {"id": 21, "english": "dormir", "russian": "спать"},
            {"id": 22, "english": "échapper", "russian": "избегать"},
            {"id": 23, "english": "écouter", "russian": "слушать"},
            {"id": 24, "english": "écrire", "russian": "писать"},
            {"id": 25, "english": "éloigner (элуанье)", "russian": "удаляться, держать вдали"},
          ]
        }, {
          "id": 4,
          "name": "Verbes. Part 4",
          "url": 'verbes_part_4',
          "words": [
            {"id": 1, "english": "embrasser", "russian": "обнимать"},
            {"id": 2, "english": "emmener (омэнэ)", "russian": "отнимать, увозить"},
            {"id": 3, "english": "empêcher", "russian": "мешать, предотвращать"},
            {"id": 4, "english": "emporter", "russian": "уносить, увозить"},
            {"id": 5, "english": "enlever", "russian": "снимать, удалять"},
            {"id": 6, "english": "entendre", "russian": "слышать, понимать"},
            {"id": 7, "english": "entrer", "russian": "входить"},
            {"id": 8, "english": "envoyer", "russian": "отправлять"},
            {"id": 9, "english": "espérer", "russian": "надеяться, ожидать"},
            {"id": 10, "english": "essayer", "russian": "пробовать"},
            {"id": 11, "english": "éviter", "russian": "избегать"},
            {"id": 12, "english": "excuser", "russian": "извинить, простить"},
            {"id": 13, "english": "expliquer", "russian": "объяснить"},
            {"id": 14, "english": "falloir", "russian": "должен, надлежать"},
            {"id": 15, "english": "fermer", "russian": "закрывать"},
            {"id": 16, "english": "filer", "russian": "прясть"},
            {"id": 17, "english": "finir", "russian": "заканчивать"},
            {"id": 18, "english": "foutre", "russian": "швырять"},
            {"id": 19, "english": "frapper", "russian": "бить, ударять"},
            {"id": 20, "english": "gagner", "russian": "достигать, зарабатывать"},
            {"id": 21, "english": "garder", "russian": "охранять, беречь"},
            {"id": 22, "english": "glisser", "russian": "скользить"},
            {"id": 23, "english": "habiter", "russian": "жить"},
            {"id": 24, "english": "ignorer", "russian": "игнорировать"},
            {"id": 25, "english": "imaginer", "russian": "воображать"},
          ]
        }, {
          "id": 5,
          "name": "Verbes. Part 5",
          "url": 'verbes_part_5',
          "words": [
            {"id": 1, "english": "importer", "russian": "привозить"},
            {"id": 2, "english": "inquiéter (анкьетэ)", "russian": "беспокоить, тревожить"},
            {"id": 3, "english": "installer", "russian": "устанавливать, помещать"},
            {"id": 4, "english": "intéresser", "russian": "интересовать"},
            {"id": 5, "english": "inviter", "russian": "приглашать"},
            {"id": 6, "english": "jeter", "russian": "бросать"},
            {"id": 7, "english": "jouer", "russian": "играть"},
            {"id": 8, "english": "jurer", "russian": "клясться, присягать, ругаться"},
            {"id": 9, "english": "lâcher", "russian": "выпускать, уронить"},
            {"id": 10, "english": "laisser", "russian": "оставлять, покидать"},
            {"id": 11, "english": "lancer", "russian": "бросать, кидать"},
            {"id": 12, "english": "lever", "russian": "поднимать"},
            {"id": 13, "english": "maintenir", "russian": "поддерживать"},
            {"id": 14, "english": "manquer", "russian": "отсутствовать, не хватать"},
            {"id": 15, "english": "marier", "russian": "женить"},
            {"id": 16, "english": "mentir (монтир)", "russian": "лгать"},
            {"id": 17, "english": "mettre", "russian": "ставить, положить"},
            {"id": 18, "english": "monter", "russian": "поднимать, дойти"},
            {"id": 19, "english": "montrer", "russian": "показывать"},
            {"id": 20, "english": "obliger", "russian": "обязывать"},
            {"id": 21, "english": "occuper", "russian": "занимать"},
            {"id": 22, "english": "offrir", "russian": "предлагать"},
            {"id": 23, "english": "oser (озэ)", "russian": "сметь"},
            {"id": 24, "english": "paraître", "russian": "казаться, выглядеть"},
            {"id": 25, "english": "passer", "russian": "тратить, просиживать"},
          ]
        }, {
          "id": 6,
          "name": "Verbes. Part 6",
          "url": 'verbes_part_6',
          "words": [
            {"id": 1, "english": "payer", "russian": "платить"},
            {"id": 2, "english": "perdre", "russian": "терять"},
            {"id": 3, "english": "permettre", "russian": "разрешать"},
            {"id": 4, "english": "plaire", "russian": "нравиться"},
            {"id": 5, "english": "pleurer", "russian": "плакать"},
            {"id": 6, "english": "pousser", "russian": "толкать"},
            {"id": 7, "english": "pouvoir", "russian": "мочь"},
            {"id": 8, "english": "prendre", "russian": "брать, принимать"},
            {"id": 9, "english": "prévenir", "russian": "предпреждать"},
            {"id": 10, "english": "prier", "russian": "молиться, просить"},
            {"id": 11, "english": "promettre", "russian": "обещать"},
            {"id": 12, "english": "protéger", "russian": "защищать"},
            {"id": 13, "english": "quitter", "russian": "покидать"},
            {"id": 14, "english": "raconter", "russian": "рассказывать"},
            {"id": 15, "english": "ramener", "russian": "возвращать"},
            {"id": 16, "english": "rappeler", "russian": "запомнить, напоминать"},
            {"id": 17, "english": "recevoir", "russian": "получать"},
            {"id": 18, "english": "reconnaître", "russian": "узнавать"},
            {"id": 19, "english": "réfléchir", "russian": "думать, размышлять"},
            {"id": 20, "english": "refuser", "russian": "отказывать"},
            {"id": 21, "english": "regarder", "russian": "смотреть"},
            {"id": 22, "english": "rejoindre", "russian": "соединять"},
            {"id": 23, "english": "remarquer", "russian": "замечать"},
            {"id": 24, "english": "remettre", "russian": "ставить, класть"},
            {"id": 25, "english": "remonter", "russian": "снова подниматься"},
          ]
        }, {
          "id": 7,
          "name": "Verbes. Part 7",
          "url": 'verbes_part_7',
          "words": [
            {"id": 1, "english": "rendre", "russian": "вернуть, возвращать"},
            {"id": 2, "english": "rentrer", "russian": "возвратиться"},
            {"id": 3, "english": "répondre", "russian": "отвечать"},
            {"id": 4, "english": "reposer", "russian": "отдыхать"},
            {"id": 5, "english": "reprendre", "russian": "снова брать"},
            {"id": 6, "english": "ressembler", "russian": "выглядить как"},
            {"id": 7, "english": "rester", "russian": "оставаться"},
            {"id": 8, "english": "retenir", "russian": "держать, запомнить"},
            {"id": 9, "english": "retirer", "russian": "вытаскивать, отзывать"},
            {"id": 10, "english": "retourner", "russian": "переворачивать"},
            {"id": 11, "english": "retrouver", "russian": "снова найти"},
            {"id": 12, "english": "réussir", "russian": "удаваться, иметь успех"},
            {"id": 13, "english": "réveiller", "russian": "будить, пробуждать"},
            {"id": 14, "english": "revenir", "russian": "возвращаться"},
            {"id": 15, "english": "rêver", "russian": "видеть сон, грезить"},
            {"id": 16, "english": "revoir", "russian": "сверять"},
            {"id": 17, "english": "rire", "russian": "смеяться"},
            {"id": 18, "english": "risquer", "russian": "рисковать"},
            {"id": 19, "english": "rouler", "russian": "катить, критить"},
            {"id": 20, "english": "sauter (сотэ)", "russian": "прыгать"},
            {"id": 21, "english": "sembler", "russian": "казаться"},
            {"id": 22, "english": "sentir", "russian": "чувствовать"},
            {"id": 23, "english": "séparer", "russian": "разделять, разлучать"},
            {"id": 24, "english": "serrer", "russian": "запирать, прижимать"},
            {"id": 25, "english": "servir", "russian": "служить, обслуживать"},
          ]
        }, {
          "id": 8,
          "name": "Verbes. Part 8",
          "url": 'verbes_part8',
          "words": [
            {"id": 1, "english": "souffrir", "russian": "страдать"},
            {"id": 2, "english": "sourire", "russian": "улыбаться"},
            {"id": 3, "english": "souvenir", "russian": "вспоминать"},
            {"id": 4, "english": "suffire", "russian": "хватать"},
            {"id": 5, "english": "suivre", "russian": "следовать, идти за"},
            {"id": 6, "english": "taire", "russian": "замалчивать, скрывать"},
            {"id": 7, "english": "tendre", "russian": "натянуть, вытягивать"},
            {"id": 8, "english": "tenir", "russian": "держать"},
            {"id": 9, "english": "tenter (тонтэ)", "russian": "попробовать, искушать"},
            {"id": 10, "english": "tirer", "russian": "тянуть"},
            {"id": 11, "english": "tomber", "russian": "падать"},
            {"id": 12, "english": "toucher", "russian": "получать, трогать"},
            {"id": 13, "english": "tourner", "russian": "поворачивать"},
            {"id": 14, "english": "traîner", "russian": "тянуть, тащить"},
            {"id": 15, "english": "traiter", "russian": "относиться, обходиться"},
            {"id": 16, "english": "traverser", "russian": "идти через, переходить"},
            {"id": 17, "english": "tromper", "russian": "обманывать"},
            {"id": 18, "english": "trouver", "russian": "находить"},
            {"id": 19, "english": "tuer", "russian": "убивать"},
            {"id": 20, "english": "utiliser", "russian": "использовать"},
            {"id": 21, "english": "valoir", "russian": "стоить, иметь ценность"},
            {"id": 22, "english": "vendre", "russian": "продавать"},
            {"id": 23, "english": "venir", "russian": "приходить"},
            {"id": 24, "english": "vivre", "russian": "жить"},
            {"id": 25, "english": "voler", "russian": "летать"},
            {"id": 26, "english": "vouloir", "russian": "хотеть"},
          ]
        }
      ]
    }
  ]
};

export default frenchVocabData;